/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ContactCard: typeof import('./src/components/profile/ContactCard.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainNavbar: typeof import('./src/components/MainNavbar.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    OverviewCard: typeof import('./src/components/profile/OverviewCard.vue')['default']
    ProfileOverviewCard: typeof import('./src/components/profile/ProfileOverviewCard.vue')['default']
    ProfileSection: typeof import('./src/components/ProfileSection.vue')['default']
    ProjectSection: typeof import('./src/components/ProjectSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceSection: typeof import('./src/components/ServiceSection.vue')['default']
    SkillSection: typeof import('./src/components/SkillSection.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TechCategory: typeof import('./src/components/profile/TechCategory.vue')['default']
    TechStackCard: typeof import('./src/components/profile/TechStackCard.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
